# LU Factorization

Copyright (C) 2021 Andreas Kloeckner

In part based on material by Edgar Solomonik

<details>
<summary>MIT License</summary>
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
</details>

In [6]:
import numpy as np
import numpy.linalg as la

np.set_printoptions(linewidth=150, suppress=True, precision=3)

In [3]:
A = np.random.randn(4, 4)
A

array([[-1.166, -1.874,  0.013,  1.471],
       [-2.169, -0.382, -0.049, -0.417],
       [ 1.131,  0.16 ,  0.869, -0.12 ],
       [ 0.421,  0.988,  1.125,  0.246]])

Initialize `L` and `U`:

In [4]:
L = np.eye(len(A))
U = np.zeros_like(A)
print(L, U)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Recall the "recipe" for LU factorization:

$$\let\B=\boldsymbol \begin{array}{cc}
     & \left[\begin{array}{cc}
       u_{00} & \B{u}_{01}^T\\
       & U_{11}
     \end{array}\right]\\
     \left[\begin{array}{cc}
       1 & \\
       \B{l}_{10} & L_{11}
     \end{array}\right] & \left[\begin{array}{cc}
       a_{00} & \B{a}_{01}\\
       \B{a}_{10} & A_{11}
     \end{array}\right]
   \end{array}$$

Find $u_{00}$ and $u_{01}$. Check `A - L@U`.

In [26]:
#clear

U[0] = A[0]



Find $l_{10}$. Check `A - L@U`.

In [30]:
#clear

L[1:,0] = A[1:,0]/U[0,0]
A - L@U


array([[ 0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.503, -1.607, -1.191, -1.309],
       [-1.077,  1.016,  0.201, -0.067],
       [-0.96 , -0.535, -1.002, -0.158]])

Recall $A_{22} =\B{l}_{21} \B{u}_{12}^T + L_{22} U_{22}$. Write the next step generic in terms of `i`.

After the step, print `A-L@U` and `remaining`.

In [55]:
print(L)
print(U)
print(A-L@U)
print((A-L@U)[1+1:,1])

[[ 1.     0.     0.     0.   ]
 [ 0.209  1.     0.     0.   ]
 [ 1.261  0.926  1.     0.   ]
 [ 1.181 -1.135 -1.477  1.   ]]
[[ 1.037  0.433  0.119  0.564]
 [ 0.     0.779  0.185 -1.812]
 [ 0.     0.    -0.95   0.237]
 [ 0.     0.     0.    -2.625]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[0. 0.]


In [32]:
i = 3
remaining = A - L@U
print(remaining)

[[ 0.     0.     0.     0.   ]
 [ 0.503 -1.607 -1.191 -1.309]
 [-1.077  1.016  0.201 -0.067]
 [-0.96  -0.535 -1.002 -0.158]]


In [58]:
#clear
U[i, i:] = remaining[i, i:]
L[i+1:,i] = remaining[i+1:,i]/U[i,i]
remaining[i+1:, i+1:] -= np.outer(L[i+1:,i], U[i, i+1:])

i = i + 1

print(remaining)
print(A-L@U)

IndexError: index 4 is out of bounds for axis 0 with size 4

In [59]:
L

array([[ 1.   ,  0.   ,  0.   ,  0.   ],
       [ 0.209,  1.   ,  0.   ,  0.   ],
       [ 1.261,  0.926,  1.   ,  0.   ],
       [ 1.181, -1.135, -1.477,  1.   ]])

In [11]:
U

array([[0.964, 1.823, 0.136, 1.129],
       [0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.187]])

In [12]:
L @ U

array([[ 0.964,  1.823,  0.136,  1.129],
       [-0.612, -1.157, -0.086, -0.716],
       [ 0.19 ,  0.359,  0.027,  0.222],
       [ 0.167,  0.316,  0.024,  0.382]])

In [13]:
A - L*U

array([[ 0.   ,  1.823,  0.136,  1.129],
       [-0.612, -1.994, -0.855,  2.135],
       [ 0.19 ,  0.162,  0.642,  0.459],
       [ 0.167,  0.26 , -1.592,  0.196]])

In [14]:
A = np.array([[1,2],[3,4]])
B = np.array([[1,2],[3,4]])
print(A@B)
print(A*B)

[[ 7 10]
 [15 22]]
[[ 1  4]
 [ 9 16]]


In [21]:
import numpy as np

def lu_decomp(A):
    n = A.shape[0]
    if n == 1:
        L = np.array([[1.0]])
        U = A.copy()
        return L, U

    A11 = A[0, 0]
    A12 = A[0, 1:]
    A21 = A[1:, 0]
    A22 = A[1:, 1:]

    # Make them 2D blocks
    L11 = np.array([[1.0]])
    U11 = np.array([[A11]])
    L12 = np.zeros((1, n-1))
    U12 = A12.reshape(1, -1)
    L21 = A21.reshape(-1, 1) / A11
    U21 = np.zeros((n-1, 1))

    # Schur complement
    S22 = A22 - np.outer(L21, U12)
    L22, U22 = lu_decomp(S22)

    # Assemble blocks
    L = np.block([[L11, L12], [L21, L22]])
    U = np.block([[U11, U12], [U21, U22]])

    return L, U


In [ ]:
A
# A - L*U
# The * operator does element-wise multiplication, not matrix multiplication.
# For matrix multiplication, use the @ operator: A - L @ U

A - L @ U

In [22]:
lu_decomp(np.array([[1, 0, 0], [2, 2, 2], [3, 3, 3]]))

(array([[1. , 0. , 0. ],
        [2. , 1. , 0. ],
        [3. , 1.5, 1. ]]),
 array([[1., 0., 0.],
        [0., 2., 2.],
        [0., 0., 0.]]))

In [ ]:
# Let us find the iterative solution over her

import numpy as np
A = np.random.randn(4, 4)
L = np.eye(4)
U = np.zeros((4, 4))

# First row/column
U[0] = A[0]
L[1:, 0] = A[1:, 0] / U[0][0]

# Initialize "remaining" as copy and update Schur complement for step 0
remaining = A.copy()
remaining[1:, 1:] -= np.outer(L[1:, 0], U[0, 1:])


# Loop over next pivots
for i in range(1, 4):
    U[i, i:] = remaining[i, i:]
    L[i+1:, i] = remaining[i+1:, i] / U[i, i]
    remaining[i+1:, i+1:] -= np.outer(L[i+1:, i], U[i, i+1:])

print("L=\n", L)
print("U=\n", U)
print("Check L @ U:\n", L @ U)
print("Original A:\n", A)
print("Error:\n", L @ U - A)


L=
 [[ 1.     0.     0.     0.   ]
 [ 0.209  1.     0.     0.   ]
 [ 1.261  0.926  1.     0.   ]
 [ 1.181 -1.135 -1.477  1.   ]]
U=
 [[ 1.037  0.433  0.119  0.564]
 [ 0.     0.779  0.185 -1.812]
 [ 0.     0.    -0.95   0.237]
 [ 0.     0.     0.    -2.625]]
Check L @ U:
 [[ 1.037  0.433  0.119  0.564]
 [ 0.216  0.869  0.209 -1.695]
 [ 1.308  1.268 -0.629 -0.73 ]
 [ 1.224 -0.373  1.333 -0.25 ]]
Original A:
 [[ 1.037  0.433  0.119  0.564]
 [ 0.216  0.869  0.209 -1.695]
 [ 1.308  1.268 -0.629 -0.73 ]
 [ 1.224 -0.373  1.333 -0.25 ]]
Error:
 [[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0. -0.]
 [ 0.  0.  0. -0.]]


In [2]:
import numpy as np
def LU_decomposition(A):
    L = np.eye(len(A))
    U = np.zeros_like(A)

    U[0] = A[0]
    L[1: , 0] = (A[1:, 0] / U[0][0])
    remaining = A.copy()
    remaining[1:, 1:] =  remaining[1:, 1:] - np.outer(L[1:, 0] , U[0, 1:])

    for i in range(1, len(A)):
        if (i == 2):
            print(L)
            print(U)
        U[i, i:]= remaining[i, i:]
        L[i + 1:, i] = remaining[i + 1:, i] / U[i][i]
        remaining[i + 1:, i + 1:] = remaining[i + 1:, i + 1:] - np.outer(L[i + 1:, i], U[i, i + 1:])
    
    # print(L, U)
A = np.array([[-0.777, 0.541, 0.513, -0.996], [0.047, 0.916, 1.295, 0.415],[0.401, -0.05,1.669, 0.689], [0.737, 0.825, -0.605, -0.518]])
val = LU_decomposition(A)




    # [a_00 a_01] = [1    ,  0] @    [u_00, u_01]
    # [a_10, a_11]  [l_10, l_11]      [0,   u_11]

    # [a_00 a_01] = [u_00, u_01]  
    # [a_10, a_11]  [l_10 * u_00, l_10 * u_01 + l_11 * u_11]



[[ 1.          0.          0.          0.        ]
 [-0.06048906  1.          0.          0.        ]
 [-0.51608752  0.24159103  1.          0.        ]
 [-0.94851995  1.41047182  0.          1.        ]]
[[-0.777       0.541       0.513      -0.996     ]
 [ 0.          0.94872458  1.32603089  0.3547529 ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]]


In [11]:
import numpy as np

A = np.array([[-0.777, 0.541, 0.513, -0.996], [0.047, 0.916, 1.295, 0.415], [0.401, -0.05, 1.669, 0.689], [0.737, 0.825, -0.605, -0.518]])
L = np.eye(4)
U = np.zeros((4, 4))

# First row/column
# U[0] = A[0]
# L[1:, 0] = A[1:, 0] / U[0][0]

# # Initialize "remaining" as copy and update Schur complement for step 0
remaining = A.copy()
# remaining[1:, 1:] -= np.outer(L[1:, 0], U[0, 1:])


# Loop over next pivots
for i in range(2):
    U[i, i:] = remaining[i, i:]
    L[i + 1:, i] = remaining[i + 1:, i] / U[i][i]
    remaining[i + 1:, i + 1:] = remaining[i + 1:, i+ 1:] - np.outer(L[i + 1:, i], U[i, i +1:])

    
print("L=\n", L)
print("U=\n", U)
print("Check L @ U:\n", L @ U)
print("Original A:\n", A)
print("Error:\n", L @ U - A)


L=
 [[ 1.     0.     0.     0.   ]
 [-0.06   1.     0.     0.   ]
 [-0.516  0.242  1.     0.   ]
 [-0.949  1.41   0.     1.   ]]
U=
 [[-0.777  0.541  0.513 -0.996]
 [ 0.     0.949  1.326  0.355]
 [ 0.     0.     0.     0.   ]
 [ 0.     0.     0.     0.   ]]
Check L @ U:
 [[-0.777  0.541  0.513 -0.996]
 [ 0.047  0.916  1.295  0.415]
 [ 0.401 -0.05   0.056  0.6  ]
 [ 0.737  0.825  1.384  1.445]]
Original A:
 [[-0.777  0.541  0.513 -0.996]
 [ 0.047  0.916  1.295  0.415]
 [ 0.401 -0.05   1.669  0.689]
 [ 0.737  0.825 -0.605 -0.518]]
Error:
 [[ 0.     0.     0.     0.   ]
 [ 0.     0.     0.    -0.   ]
 [ 0.     0.    -1.613 -0.089]
 [ 0.     0.     1.989  1.963]]


In [ ]:
# We now move on to work on a case of Cholesky over here
# I will first implement a whole LU factorization from start to end over here and then we will look into some more questions


[[1. 1.]
 [0. 0.]]


In [40]:
A =  np.array([
    [4, 1, 1, 1],
    [1, 3, 0, 1],
    [1, 0, 2, 1],
    [1, 1, 1, 3]
], dtype=float)


L = np.eye(len(A))
U = np.zeros(A.shape)
print (A.shape, L.shape, U.shape)
# We will make over here 
remaining = A.copy()

for i in range(0, len(A)):
    U[i, i:] = remaining[i, i:]
    L[i + 1:, i] = remaining[i + 1:, i] / U[i][i]
    remaining[i + 1:, i + 1:] = remaining[i + 1:, i + 1:] - np.outer(L[i + 1:, i], U[i, i + 1:])
    # print("Error:\n", L @ U - A)
b = np.array([1,1,1,1])
# We will do forward and backward substitution
def forward_substitution (A, b):
    x = [0] * len(A)
    for i in range(len(A)):
        x_val = A[i][i]
        b_val = b[i]
        for j in range(i):
            b_val -= A[i][j] * x[j]
        x[i] = b_val/x_val
    return x
val = forward_substitution(L, b)
def backward_substitution(A, b):
    x = [0] * len(A)
    for i in range(len(A) - 1, -1 , -1):
        x_val = A[i][i]
        b_val = b[i]
        for j in range(i + 1, len(A)):
            b_val -= A[i][j] * x[j]
        x[i] = b_val/x_val
    return x
x = backward_substitution(U, val)

val = la.solve(A, b)
print(A - L@U)


(4, 4) (4, 4) (4, 4)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# Let us try to write the code for Cholesky factorization over here


L = np.zeros(A.shape)
remaining = A.copy()
for i in range(len(A)):
    L[i][i] = np.sqrt(remaining[i][i])
    L[i + 1:, i] = remaining[i + 1:, i] / L[i][i]
    remaining[i + 1:, i + 1:] =  (remaining[i + 1:, i + 1:] -np.outer(L[i + 1:, i], L[i + 1:, i])) 
print(A - L@L.T)

# [l11,  0]    @ [l11, l12.T]
# [l21, L22]     [0,   L22.T]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
import numpy as np
import scipy
A = np.random.randn(4, 4)
# L = np.eye(4)
# U = np.zeros_like(A)
# remaining = np.copy(A)
# for i in range(len(A)):
#     U[i, i:] = remaining[i, i:]
#     L[i + 1:,  i] = remaining[i + 1:, i] / U[i][i]
#     remaining[i + 1:, i + 1:] = remaining[i + 1:, i + 1:] - np.outer(L[i + 1:, i] , U [i, i + 1:])

# We now move on to do a coding analysis of Cholesky over here for this question

A =  np.array([
    [4, 1, 1, 1],
    [1, 3, 0, 1],
    [1, 0, 2, 1],
    [1, 1, 1, 3]
], dtype=float)

# L = np.zeros(A.shape)
# remaining = A.copy()
# # Use remaining for everything inside over here do not use A inside the blocks here.
# for i in range(len(A)):
#     L[i][i] = np.sqrt(remaining[i][i])
#     L[i + 1:, i] = remaining[i + 1:, i] / L[i][i]
#     remaining[i + 1:, i + 1:] = remaining[i + 1:, i + 1:] - np.outer(L[i + 1:, i], L[i + 1:, i])

# print(A - L @ L.T)
b = np.array([1, 1,1, 1])
P, L, U = scipy.linalg.lu(A)
b2 = P @ b

# Step 2: Forward substitution
y = scipy.linalg.solve_triangular(L, b2, lower=True)

# Step 3: Backward substitution
x = scipy.linalg.solve_triangular(U, y)
print(b - A @ x)

[ 0.00000000e+00  0.00000000e+00 -2.22044605e-16  0.00000000e+00]
