# Power Iteration and its Variants

Copyright (C) 2020 Andreas Kloeckner

<details>
<summary>MIT License</summary>
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
</details>

In [1]:
import numpy as np
import numpy.linalg as la


np.set_printoptions(precision=3, linewidth=120)

Let's  prepare a matrix with some random or deliberately chosen eigenvalues:

In [27]:
n = 6

if 1:
    np.random.seed(70)
    eigvecs = np.random.randn(n, n)
    eigvals = np.sort(np.random.randn(n))
    # Uncomment for near-duplicate largest-magnitude eigenvalue
    # eigvals[1] = eigvals[0] + 1e-3

    A = eigvecs.dot(np.diag(eigvals)).dot(la.inv(eigvecs))
    print(eigvals)
    
else:
    # Complex eigenvalues
    np.random.seed(40)
    A = np.random.randn(n, n)
    print(la.eig(A)[0])

[-2.668 -0.958 -0.33  -0.292 -0.186 -0.144]


Let's also pick an initial vector:

In [28]:
#clear
x0 = np.random.randn(n)
x0

array([ 2.269,  0.664,  0.899, -0.366,  0.463,  0.08 ])

### Power iteration

In [29]:
x = x0

Now implement plain power iteration.

In [30]:
#clear
for i in range(20):
    x = A @ x
    print(x)

[-7.705 22.151  2.865 -4.648  4.043 11.651]
[ 19.254 -66.76  -10.275  13.745 -12.354 -31.851]
[-50.872 180.931  28.982 -38.003  32.878  84.804]
[ 135.725 -484.052  -78.458  103.027  -87.053 -226.183]
[-362.275 1292.214  210.269 -276.615  231.404  603.437]
[  966.69  -3447.945  -561.808   739.696  -616.452 -1609.861]
[-2579.07   9198.61   1499.54  -1974.989  1643.638  4294.662]
[  6880.334 -24539.336  -4001.041   5270.259  -4383.84  -11456.774]
[-18354.595  65463.009  10674.137 -14060.82   11693.775  30562.786]
[  48963.909 -174633.058  -28475.596   37510.904  -31194.161  -81530.956]
[-130618.864  465860.62    75963.646 -100067.48    83214.419  217496.239]
[  348445.777 -1242754.094  -202645.16    266946.529  -221986.341  -580204.159]
[-929531.949 3315234.721  540587.199 -712121.531  592181.424 1547782.299]
[ 2479667.045 -8843889.704 -1442098.59   1899693.011 -1579732.736 -4128943.082]
[-6614886.466 23592411.656  3847016.323 -5067719.196  4214175.002 11014579.211]
[ 17646208.664 -629363

* What's the problem with this method?
* Does anything useful come of this?
* How do we fix it?

### Normalized power iteration

Back to the beginning: Reset to the initial vector.

In [31]:
x0 = np.random.randn(n)
x = x0
print(x)
eigvals, eigvecs = np.linalg.eig(A)
print(eigvals)

[-0.345  0.964  0.971 -0.796  0.785  0.307]
[-2.668 -0.958 -0.144 -0.186 -0.33  -0.292]


Implement normalized power iteration.

In [32]:
#clear
for i in range(20):
    x = A @ x
    nrm = la.norm(x)
    x = x/nrm
    print(x)

print(nrm)

[ 2.693e-01 -7.490e-01 -2.115e-01  4.139e-01 -1.946e-04 -3.878e-01]
[-0.245  0.82   0.178 -0.289  0.082  0.382]
[ 0.239 -0.838 -0.155  0.223 -0.125 -0.388]
[-0.237  0.843  0.144 -0.197  0.141  0.392]
[ 0.237 -0.844 -0.14   0.187 -0.147 -0.393]
[-0.237  0.845  0.139 -0.183  0.15   0.394]
[ 0.237 -0.845 -0.138  0.182 -0.15  -0.394]
[-0.237  0.845  0.138 -0.182  0.151  0.394]
[ 0.237 -0.845 -0.138  0.182 -0.151 -0.394]
[-0.237  0.845  0.138 -0.181  0.151  0.394]
[ 0.237 -0.845 -0.138  0.181 -0.151 -0.394]
[-0.237  0.845  0.138 -0.181  0.151  0.394]
[ 0.237 -0.845 -0.138  0.181 -0.151 -0.394]
[-0.237  0.845  0.138 -0.181  0.151  0.394]
[ 0.237 -0.845 -0.138  0.181 -0.151 -0.394]
[-0.237  0.845  0.138 -0.181  0.151  0.394]
[ 0.237 -0.845 -0.138  0.181 -0.151 -0.394]
[-0.237  0.845  0.138 -0.181  0.151  0.394]
[ 0.237 -0.845 -0.138  0.181 -0.151 -0.394]
[-0.237  0.845  0.138 -0.181  0.151  0.394]
2.667650992109833


### Checking convergence

In [33]:
x0 = np.random.randn(n)
x = x0
errors = []
coeffs = la.solve(eigvecs, x0)

for i in range(10):
    x = A @ x
    errors.append(
        la.norm(x/eigvals[0]**(i+1) - coeffs[0]*eigvecs[:,0], 2))
    print("coefficients:", la.solve(eigvecs, x/la.norm(x,2)))

conv_factor = eigvals[1]/eigvals[0]

errors = np.array(errors)
for i in range(len(errors)-1):
    print(f"{i=}: {errors[i]=:.6e}, {errors[i+1]/errors[i]=:.6g}, {conv_factor=:.6g}")

coefficients: [ 1.099 -0.011 -0.058  0.118 -0.173 -0.031]
coefficients: [-1.01   0.004  0.003 -0.008  0.02   0.003]
coefficients: [ 1.001e+00 -1.340e-03 -1.546e-04  5.232e-04 -2.418e-03 -3.397e-04]
coefficients: [-1.000e+00  4.807e-04  8.347e-06 -3.651e-05  2.990e-04  3.708e-05]
coefficients: [ 1.000e+00 -1.726e-04 -4.510e-07  2.550e-06 -3.700e-05 -4.051e-06]
coefficients: [-1.000e+00  6.198e-05  2.438e-08 -1.781e-07  4.579e-06  4.427e-07]
coefficients: [ 1.000e+00 -2.226e-05 -1.317e-09  1.244e-08 -5.668e-07 -4.838e-08]
coefficients: [-1.000e+00  7.992e-06  7.121e-11 -8.691e-10  7.016e-08  5.286e-09]
coefficients: [ 1.000e+00 -2.870e-06 -3.850e-12  6.071e-11 -8.684e-09 -5.777e-10]
coefficients: [-1.000e+00  1.031e-06  2.093e-13 -4.243e-12  1.075e-09  6.313e-11]
i=0: errors[i]=6.377053e-01, errors[i+1]/errors[i]=0.130125, conv_factor=0.359107
i=1: errors[i]=8.298113e-02, errors[i+1]/errors[i]=0.141745, conv_factor=0.359107
i=2: errors[i]=1.176219e-02, errors[i+1]/errors[i]=0.216129, con

* Now try the matrix variants above.

------
### Inverse iteration

What if we want the eigenvalue closest to a give value $\sigma$?

Once again, reset to the beginning.

In [ ]:
#clear
x0 = np.random.randn(3)
x = x0/la.norm(x0)

sigma = 1
A_sigma = A-sigma*np.eye(A.shape[0])
for i in range(30):
    x = la.solve(A_sigma, x)
    nrm = la.norm(x)
    x = x/nrm
    print(x)

[ 0.184 -0.983  0.004]
[ 0.271 -0.963  0.003]
[ 0.389 -0.921  0.002]
[ 0.535 -0.845  0.001]
[ 0.688 -0.725  0.001]
[ 8.182e-01 -5.749e-01  5.706e-04]
[ 9.056e-01 -4.242e-01  3.158e-04]
[ 9.545e-01 -2.981e-01  1.664e-04]
[ 9.790e-01 -2.038e-01  8.535e-05]
[ 9.905e-01 -1.375e-01  4.317e-05]
[ 9.957e-01 -9.213e-02  2.170e-05]
[ 9.981e-01 -6.157e-02  1.088e-05]
[ 9.992e-01 -4.109e-02  5.444e-06]
[ 9.996e-01 -2.740e-02  2.723e-06]
[ 9.998e-01 -1.827e-02  1.362e-06]
[ 9.999e-01 -1.218e-02  6.810e-07]
[ 1.000e+00 -8.123e-03  3.405e-07]
[ 1.000e+00 -5.415e-03  1.703e-07]
[ 1.000e+00 -3.610e-03  8.513e-08]
[ 1.000e+00 -2.407e-03  4.257e-08]
[ 1.000e+00 -1.605e-03  2.128e-08]
[ 1.000e+00 -1.070e-03  1.064e-08]
[ 1.000e+00 -7.131e-04  5.321e-09]
[ 1.000e+00 -4.754e-04  2.660e-09]
[ 1.000e+00 -3.169e-04  1.330e-09]
[ 1.000e+00 -2.113e-04  6.651e-10]
[ 1.000e+00 -1.409e-04  3.326e-10]
[ 1.000e+00 -9.391e-05  1.663e-10]
[ 1.000e+00 -6.261e-05  8.314e-11]
[ 1.000e+00 -4.174e-05  4.157e-11]


--------------
### Rayleigh quotient iteration

Can we feed an estimate of the current approximate eigenvalue back into the calculation? (Hint: Rayleigh quotient)

Reset once more.

In [34]:
x = x0/la.norm(x0)

Run this cell in-place (Ctrl-Enter) many times.

In [36]:
#clear
for i in range(10):
    sigma = np.dot(x, np.dot(A, x))/np.dot(x, x)
    x = la.solve(A-sigma*np.eye(n), x)
    x = x/la.norm(x)
    print(x, sigma)

[ 0.518  0.379 -0.086 -0.583  0.145 -0.469] -0.14418092560962564
[-0.518 -0.379  0.086  0.583 -0.145  0.469] -0.14418092560962506
[-0.518 -0.379  0.086  0.583 -0.145  0.469] -0.14418092560962598
[ 0.518  0.379 -0.086 -0.583  0.145 -0.469] -0.14418092560962448
[ 0.518  0.379 -0.086 -0.583  0.145 -0.469] -0.14418092560962734
[-0.518 -0.379  0.086  0.583 -0.145  0.469] -0.1441809256096223
[ 0.518  0.379 -0.086 -0.583  0.145 -0.469] -0.14418092560962306
[ 0.518  0.379 -0.086 -0.583  0.145 -0.469] -0.14418092560962414
[-0.518 -0.379  0.086  0.583 -0.145  0.469] -0.14418092560962323
[-0.518 -0.379  0.086  0.583 -0.145  0.469] -0.1441809256096235


* What's a reasonable stopping criterion?
* Computational downside of this iteration?